<!DOCTYPE html>
<html>
	<head>

		<!-- Basic -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">	

		<title>SEN T.A ORJI| ANNUAL SCHOLARSHIP 2021 EDITION PORTAL - PRIVACY POLICY</title>	

		<meta name="keywords" content="Scholarship" />
		<meta name="description" content="ANNUAL SCHOLARSHIP 2021 EDITION PORTAL">
		<meta name="author" content="WBL IT SOLUTIONS">

		<!-- Favicon -->
		<link rel="shortcut icon" href="../img/logo-red.png" type="image/x-icon" />
		<link rel="apple-touch-icon" href="../img/apple-touch-icon.png">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

		<!-- Web Fonts  -->
		<link id="googleFonts" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light&display=swap" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="../vendor/fontawesome-free/css/all.min.css">
		<link rel="stylesheet" href="../vendor/animate/animate.compat.css">
		<link rel="stylesheet" href="../vendor/simple-line-icons/css/simple-line-icons.min.css">
		<link rel="stylesheet" href="../vendor/owl.carousel/assets/owl.carousel.min.css">
		<link rel="stylesheet" href="../vendor/owl.carousel/assets/owl.theme.default.min.css">
		<link rel="stylesheet" href="../vendor/magnific-popup/magnific-popup.min.css">

		<!-- Theme CSS -->
		<link rel="stylesheet" href="../css/theme.css">
		<link rel="stylesheet" href="../css/theme-elements.css">
		<link rel="stylesheet" href="../css/theme-blog.css">
		<link rel="stylesheet" href="../css/theme-shop.css">

		<!-- Skin CSS -->
		<link id="skinCSS" rel="stylesheet" href="../css/skins/default.css">
        {{-- <link id="skinCSS" rel="stylesheet" href="css/skins/skin-corporate-6.css"> --}}


		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="../css/custom.css">

		<!-- Head Libs -->
		<script src="../vendor/modernizr/modernizr.min.js"></script>

	</head>
	<body data-plugin-page-transition>

		<div class="body">

            <x-header></x-header>

			<div role="main" class="main">

				<section class="page-header page-header-modern bg-color-light-scale-1 page-header-lg">
					<div class="container">
						<div class="row">
							<div class="col-md-12 align-self-center p-static order-2 text-center">
								<h1 class="font-weight-bold text-dark">Privacy Notice</h1>
							</div>
							<div class="col-md-12 align-self-center order-1">
								<ul class="breadcrumb d-block text-center">
									<li><a href="/">Home</a></li>
									<li class="active">Privacy Policy</li>
								</ul>
							</div>
						</div>
					</div>
				</section>

				<div class="container py-4">

					<div class="row">
						<div class="col">
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>1.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>OUR APPROACH TO PRIVACY</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>1.1 &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;The Senator T. A. Orji Annual Scholarship establishment (&quot;<strong>we</strong>&quot;, &quot;<strong>our</strong>&quot; or &quot;<strong>us</strong>&quot;) is committed to respecting your privacy. This privacy notice sets out how we collect, store, transfer, share, disclose, and use Personal Information that identifies or is associated with you (&quot;<strong>Personal Information</strong>&quot;).&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>1.2 &nbsp; &nbsp; &nbsp; We provide scholarship funds to university students in the Abia Central Senatorial District through the portal on our website, that allows you to upload your Personal Information for processing.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>1.3 &nbsp; &nbsp; &nbsp; &nbsp;This privacy notice applies to the Annual Scholarship Portal. Please ensure that you have thoroughly read and understood this privacy notice <em>before</em> accessing or using the portal to make your submission for the scholarship funds.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>2.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>WHO IS RESPONSIBLE FOR THE USE OF YOUR PERSONAL INFORMATIONPERSONAL INFORMATION</strong>&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Times New Roman",serif;'>We are the controller of the Personal Information we hold about you in connection with your application for scholarship funds on our portal. This means that we determine and are responsible for how your Personal Information is used.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>3.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>HOw WE Process Personal Information and on Which BAsis</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>3.1 &nbsp; &nbsp; &nbsp; &nbsp;We will only collect, store, transfer, share, disclose, and use your Personal Information which are relevant for the granting of scholarship funds and in accordance with relevant data protection laws in Nigeria including the Nigeria Data Protection Regulation, 2019, the 1999 Constitution of the Federal Republic of Nigeria (as amended) and regulations issued by the NITDA. This means that we will process the following data:</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(a) &nbsp; &nbsp; &nbsp; &nbsp;<strong>Information you submit into the application fields.</strong> We will collect information submitted on the portal in order to assess your suitability in respect of the scholarship funds. This information includes your full name, contact details, State/Local Government Area Certificate, name of university, social media URL, admission letter and Identification Card and is processed based on your Consent.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>3.2 &nbsp; &nbsp; &nbsp; We may anonymise and aggregate any of the Personal Information we collect (so that we can no longer identify you, directly or indirectly). We may use anonymised information for purposes that include testing our IT systems, research, data analysis and improving the portal.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>4.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>How long we will store your personal information</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>4.1 &nbsp; &nbsp; &nbsp; We will usually store the Personal Information we collect about you for no longer than necessary for the purposes of assessing your suitability to receive the scholarship grant, and in satisfying any legal or reporting requirements.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>4.2 &nbsp; &nbsp; &nbsp; To determine the appropriate retention period for Personal Information, we consider the amount, nature, and sensitivity of the Personal Information, the potential risk of harm from unauthorised use or disclosure of your Personal Information, the purposes for which we process your Personal Information and the applicable legal requirements.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>5.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>RECIPIENTS OF PERSONAL INFORMATION</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Times New Roman",serif;'>We may share and disclose your Personal Information with the following (as required in accordance with the purposes set out in the <strong>Annex</strong>):</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(a) &nbsp; &nbsp; &nbsp; &nbsp;<strong>Our affiliates</strong>. We may share Personal Information with our affiliates within the country for the purpose assessing your suitability for the receipt of scholarship funds.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(b) &nbsp; &nbsp; &nbsp; &nbsp;<strong>Law enforcement, regulators and other parties for legal reasons</strong>. We may share your Personal Information with third parties as required by law or if we reasonably believe that such action is necessary: (i) to comply with the law, or to comply with the reasonable requests of law enforcement and other government agencies; (ii) to detect and investigate illegal activities and breaches of agreements (iii) to protect the security or integrity of our establishment; and/or (iv) to exercise or protect our claims, rights and property.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(c) &nbsp; &nbsp; &nbsp; &nbsp; <strong>Otherwise with consent.</strong> We may disclose your Personal Information to certain other third parties with your explicit consent.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>6.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>STORING&nbsp;</strong></span><strong><span style='font-family:"Times New Roman",serif;'>AND TRANSFERRING&nbsp;</span></strong><strong><span style='font-family:"Times New Roman",serif;'>YOUR PERSONAL INFORMATION</span></strong></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>6.1 &nbsp; &nbsp; &nbsp;<strong>Storage of Data, Security and Transfers</strong>. We implement technical and organisational measures to protect your Personal Information that&nbsp;</span><span style='font-family:"Times New Roman",serif;color:#262626;'>we collect, store, transfer, use and share/disclose</span><span style='font-family:"Times New Roman",serif;'>&nbsp;against accidental or unlawful destruction, loss, alteration, and unauthorised disclosure or access. These efforts include but are not necessarily limited to: (i) storing your Personal Data in secure operating environments that are not available to the public and that are only accessible to authorized personnel; and (ii) verifying the identities of registered users before they can access the Personal Data we maintain about them</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Times New Roman",serif;color:black;'>In the event that any Personal Information under our control is compromised as a result of a breach of security, we will take reasonable steps to investigate the situation and where appropriate, notify those individuals whose Personal Information may have been compromised and take other steps, in accordance with the NDPR and any other applicable laws and regulations.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>6.2 &nbsp; &nbsp; &nbsp;If you wish to enquire further about the safeguards used, please contact us using the details set out at the end of this privacy notice.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>7.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>your rights in respect of your personal information</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>7.1 &nbsp; &nbsp; &nbsp; &nbsp;In accordance with applicable privacy law, you have the following rights in respect of your Personal Information that we hold:</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(a) &nbsp; &nbsp; &nbsp; &nbsp;<strong>Right of consent or refusal to give consent</strong>: Before we start collecting your Personal Information, you have the right to refuse to grant us consent when you click submit. &nbsp;We shall collect, store, transfer, share/disclose and use your Personal Information only upon receiving your application through our portal. &nbsp;You give your consent for our collection and processing of your Personal Information upon clicking the &lsquo;Submit&rsquo; button on the portal. Similarly, you may choose to refuse to give your consent by not submitting your application for the scholarship funds. You understand that once you click on the &lsquo;Submit&rsquo; option, this will amount to you granting us your consent in writing, for the collection and usage of your Personal Information in accordance with this Privacy Policy.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Further, you also certify that&nbsp;</span><span style='font-family:"Times New Roman",serif;color:#262626;'>by clicking &lsquo;Submit&rsquo;, each Personal Information that you provide to us is correct, accurate, recent, and valid.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(b) &nbsp; &nbsp; &nbsp; <strong>Right of access</strong>. You have the right to obtain access to your Personal Information that we collect, store, transfer, share/disclose and use. This includes the right to obtain:</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.5in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(i) &nbsp; &nbsp; &nbsp; &nbsp; confirmation of whether we are processing your Personal Information;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.5in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(ii) &nbsp; &nbsp; &nbsp; &nbsp;information about the categories of Personal Information we are processing, the purposes for which we process your Personal Information and information as to how we determine applicable retention periods;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.5in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(iii) &nbsp; &nbsp; &nbsp; &nbsp;information about the categories of recipients with whom we may share your Personal Information and if those recipients are located in third countries; and</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.5in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(iv) &nbsp; &nbsp; &nbsp; &nbsp;a copy of the Personal Information we hold about you.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(c) &nbsp; &nbsp; &nbsp; &nbsp;<strong>Right of portability</strong>. You have the right, in certain circumstances, to receive a copy of the Personal Information you have provided to us in a structured, commonly used, machine-readable format that supports re-use, or to request the transfer of your Personal Information to another person.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(d) &nbsp; &nbsp; &nbsp; &nbsp;<strong>Right to rectification</strong>. You have the right to obtain rectification of any inaccurate, outdated, or incomplete Personal Information we hold about you without undue delay&nbsp;</span><span style='font-family:"Times New Roman",serif;color:#262626;'>by contacting us</span><span style='font-family:"Times New Roman",serif;'>. &nbsp;However, you understand and agree that we do not hold any responsibility towards the accuracy or authenticity of the user data which you have submitted or we have collected through your use of the application portal.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(e) &nbsp; &nbsp; &nbsp; &nbsp;<strong>Right to erasure</strong>. You have the right to require us to erase your Personal Information without undue delay if the continued processing of that Personal Information is not justified.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(f) &nbsp; &nbsp; &nbsp; &nbsp; <strong>Right to restriction</strong>. You have the right to require us to limit the purposes for which we collect, store, transfer, share/disclose and use your Personal Information (for example, where the accuracy of the personal data is contested by you), for a period of time that enables us to verify the accuracy of that personal data.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(g) &nbsp; &nbsp; &nbsp; &nbsp;<strong>RIGHT TO OBJECT</strong>. You also have the right to object to any collection, storage, transfer, share/disclosure and usage of your Personal Information, at any time, where your objection is raised on grounds relating to your particular situation. Should you decide to object to the collection, storage, transfer, share/disclosure and usage of your Personal Information, we will stop the collection, storage, transfer, share/disclosure and usage of your Personal Information upon your request, unless we are required to such disclosure of your Personal Information for the purpose of the enforcement of the applicable laws and regulations by the basis of a lawful request from an authorized governmental official.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:1.0in;line-height:125%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>(h) &nbsp; &nbsp; &nbsp; <strong>Right to withdraw consent</strong>. We do not need your consent for all of the processing activities we undertake. However, if we rely on your consent as the lawful basis for our processing, and you have provided such consent for the processing of your Personal Information, you have the right to withdraw your consent at any time. If you withdraw your consent this will not affect the lawfulness of our use of your Personal Information before your withdrawal. You can withdraw your consent to the processing of your Personal Information for the purpose of assessing your suitability for receiving the scholarship fund, by contacting us. If you withdraw your consent, we will no longer be able process your information with respect to the receipt of the scholarship funds.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>7.2 &nbsp; &nbsp; &nbsp; &nbsp;If you wish to exercise one of these rights, please contact us using the contact details at the end of this privacy notice.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>7.3 &nbsp; &nbsp; &nbsp; Due to the confidential nature of data processing we may ask you to provide proof of identity when exercising the above rights.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>7.4 &nbsp; &nbsp; &nbsp; <strong>Right to lodge a complaint</strong>. You also have the right to lodge a complaint with our data protection authority, the National Information Technology Development Agency (NITDA), which can be accessed&nbsp;</span><a href="https://nitda.gov.ng/contact/"><span style='font-family:"Times New Roman",serif;'>here</span></a><span style='font-family:"Times New Roman",serif;'>,</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>8.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; <strong>OUR POLICY TOWARDS CHILDREN</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Times New Roman",serif;'>Our service and application portal is not directly offered to any child as defined by applicable laws and regulations of each jurisdiction (a &ldquo;Child&rdquo; or &ldquo;Children&rdquo;). Our scholarship fund is strictly not intended for Children and we do not knowingly collect or solicit Personal Information from Children. In the event that we learn that we have inadvertently collected Personal Information from a Child, we will delete that information as quickly as possible. If you believe that we might have any information from a Child, please contact us using the details at the end of the privacy notice.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>9.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; <strong>CHANGES TO THIS PRIVACY NOTICE</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Times New Roman",serif;'>We may update this privacy notice from time to time, and you should review this page carefully and periodically. When we change this privacy notice, we will update the &quot;last modified&quot; date at the end of this privacy notice, and we recommend you to carefully read this Privacy Notice from time to time. Changes to this privacy notice are effective when they are posted on this page.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>10.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; <strong>NOTICE TO YOU</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Times New Roman",serif;'>If we need to provide you with information about something, whether for legal, or other scholarship-related purposes, we will select what we believe is the lawful and most effective way to get in contact with you. We will usually do this through email or by placing a notice on our website.&nbsp;</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><strong><span style='font-family:"Times New Roman",serif;'>11.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; <strong>ACKNOWLEDGMENT AND CONSENT</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;By accepting this Privacy Notice, you acknowledge that you have read and understood this Privacy Notice and you accept all of its terms and conditions. In particular, you agree and consent to us collecting, storing, transferring, sharing, disclosing, and using your Personal Information in accordance with this Privacy Notice.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;You may withdraw your consent to any or all collection, storage, transfer, share, disclosure and usage of your Personal Information at any time by giving us reasonable notice in writing by contacting us in the contact details set out below. Depending on the circumstances and the nature of the consent which you are withdrawing, you must understand and acknowledge that after such withdrawal of consent, you will no longer be considered for the receipt of our scholarship funds. A withdrawal of consent by you may result in the termination of your account or of your contractual relationship with us, with all accrued rights and obligations remaining fully reserved. Upon receipt of your notice to withdraw consent for any collection, storage, transfer, share/disclosure and usage of your personal information Personal Information, we will inform you of the likely consequences of such withdrawal so that you can decide if indeed you wish to withdraw consent.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:0in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Times New Roman",serif;'>12.</span></strong><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>CONTACTING US</strong></span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>16.1 &nbsp; &nbsp; &nbsp;Please contact&nbsp;</span><a href="mailto:contact@senatortaorji.com"><span style='font-family:"Times New Roman",serif;'>contact@senatortaorji.com</span></a><span style='font-family:"Times New Roman",serif;'>&nbsp;or&nbsp;</span><a href="mailto:scholarship@senatortaorji.com"><span style='font-family:"Times New Roman",serif;'>scholarship@senatortaorji.com</span></a><span style='font-family:"Times New Roman",serif;'>&nbsp; &nbsp; if you have any questions, comments and requests regarding this privacy notice.</span></p>
							<p style='margin-top:0in;margin-right:0in;margin-bottom:12.0pt;margin-left:.5in;line-height:15.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;text-indent:-.5in;'><span style='font-family:"Times New Roman",serif;'>16.2 &nbsp; &nbsp; &nbsp;This privacy notice was last modified on August 11, 2021</span></p>
						</div>

					</div>

				</div>

			</div>

            <x-footer></x-footer>

		</div>

		<!-- Vendor -->
		<script src="../vendor/jquery/jquery.min.js"></script>
		<script src="../vendor/jquery.appear/jquery.appear.min.js"></script>
		<script src="../vendor/jquery.easing/jquery.easing.min.js"></script>
		<script src="../vendor/jquery.cookie/jquery.cookie.min.js"></script>
		<script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
		<script src="../vendor/jquery.validation/jquery.validate.min.js"></script>
		<script src="../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
		<script src="../vendor/jquery.gmap/jquery.gmap.min.js"></script>
		<script src="../vendor/lazysizes/lazysizes.min.js"></script>
		<script src="../vendor/isotope/jquery.isotope.min.js"></script>
		<script src="../vendor/owl.carousel/owl.carousel.min.js"></script>
		<script src="../vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
		<script src="../vendor/vide/jquery.vide.min.js"></script>
		<script src="../vendor/vivus/vivus.min.js"></script>

		<!-- Theme Base, Components and Settings -->
		<script src="../js/theme.js"></script>

		<!-- Theme Custom -->
		<script src="../js/custom.js"></script>

		<!-- Theme Initialization Files -->
		<script src="../js/theme.init.js"></script>

	</body>
</html>
